# Generated by Django 5.1.3 on 2024-11-28 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tarea",
            options={
                "ordering": ["-fecha_creacion"],
                "verbose_name": "Tarea",
                "verbose_name_plural": "Tareas",
            },
        ),
        migrations.AlterField(
            model_name="tarea",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("COMPLETADA", "Completada"),
                    ("INCOMPLETA", "Incompleta"),
                ],
                default="PENDIENTE",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_estado",
                        message="Estado no válido",
                        regex="^(PENDIENTE|COMPLETADA|INCOMPLETA)$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tarea",
            name="titulo",
            field=models.CharField(
                max_length=200,
                validators=[
                    django.core.validators.MinLengthValidator(
                        3, "El título debe tener al menos 3 caracteres"
                    )
                ],
            ),
        ),
    ]
